database:
  # Database host address, default = localhost
  host: localhost
  # Database port, default = 3306
  port: 3306
  # Database name, default = minecraft
  database: minecraft
  # Database user, default = root
  user: root
  # Database password
  password: password
  # Connect to database over SSL, default = false
  enable-ssl: false
  # Overrides the size of the database connection pool, default = 10
  maximum-pool-size: 10
  # Connection timeout in milliseconds, default = maximum size of signed int
  connection-timeout: 5000


# This section allows you to configure the travelling system.
travel:
  # Should travel system be enabled? Default = true
  enable: true

  price-multiplier:
    # Default = 1.1
    value: 1.1
    # Default = true
    enable: true

# The value below must be the prefix of the region to be explored.
# This means that any region id that a player can discover must
# start with the value shown below. For example:
# - fr_region_to_be_explored
# - frRegionToBeExplored
# - frRegion_to_Be-explored
regions-prefix: fr